export { ApiError } from "./errors.js";
export type { ApiErrorOptions } from "./errors.js";
export { DEFAULT_BASE_URL, SvgiconsClient } from "./client.js";
export type {
  BinaryRequester,
  FetchLike,
  HttpMethod,
  JsonRequester,
  QueryParams,
  QueryValue,
  RequestOptions,
  SvgiconsClientOptions,
} from "./client.js";
export type {
  Account,
  AddIconResponse,
  BulkAddIconsResponse,
  ColorPolicy,
  CreateExportRequest,
  DataResponse,
  ErrorResponse,
  ExportFormat,
  ExportOptions,
  ExportResponse,
  Icon,
  IconColorMode,
  IconPngDensity,
  IconResponse,
  IconSearchResponse,
  IconSearchResult,
  IconSet,
  IconSvgResponse,
  IconWithSvg,
  Id,
  JsonPrimitive,
  JsonValue,
  MeResponse,
  NamingPolicy,
  Pagination,
  PngBackgroundType,
  PngDensity,
  PngExportRequest,
  PngExportResponse,
  PngOptions,
  PngSize,
  ProApiScope,
  ProApiUser,
  ProjectKit,
  ProjectKitDetail,
  ProjectKitDetailResponse,
  ProjectKitExport,
  ProjectKitFramework,
  ProjectKitIcon,
  ProjectKitListResponse,
  ProjectKitOptions,
  ProjectKitSummaryResponse,
  ProjectKitWriteRequest,
  RemoveIconResponse,
  ScopeError,
  ScopeListResponse,
  ScopeValue,
  SearchIconsParams,
  SvgiconsBinaryResponse,
  TokenSummary,
  ValidationError,
} from "./types.js";
export type { ExportPngParams, GetIconParams, IconsResource } from "./icons.js";
export type { MeResource } from "./me.js";
export type {
  AddBulkProjectKitIconsParams,
  AddProjectKitIconParams,
  CreateProjectKitExportParams,
  CreateProjectKitParams,
  GetProjectKitParams,
  ProjectKitExportParams,
  ProjectKitExportsResource,
  ProjectKitIconParams,
  ProjectKitIconsResource,
  ProjectKitIdParams,
  ProjectKitsResource,
  UpdateProjectKitParams,
} from "./project-kits.js";
export type { ScopesResource } from "./scopes.js";
export type { SearchResource } from "./search.js";
